version: "3.7"
services:
  flask_app:
    build: './flask_app'
    volumes:
      - ./flask_app:/flask_app
      - ./core_app:/flask_app/core_app  # Mount the core_app directory into the container
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: './worker'
    volumes:
    - ./worker:/worker
    - ./core_app:/worker/core_app  # Mount the core_app directory into the container
    user: nobody
    depends_on:
      - redis
      - flask_app


  redis:
    image: 'redis:4-alpine'
    ports:
      - '6379:6379'
